apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: py-new-m
  namespace: default
spec:
  selector:
    matchLabels:
      app: py-new
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 5s

